-- MySQL Script generated by MySQL Workbench
-- dom 30 ene 2022 19:36:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exercici1-Optica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Exercici1-Optica` ;

-- -----------------------------------------------------
-- Schema Exercici1-Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exercici1-Optica` ;
USE `Exercici1-Optica` ;

-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Direccion` (
  `direccion_id` INT NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(6) NOT NULL,
  `pais` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`direccion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Proveedor` (
  `proveedor_id` INT NOT NULL AUTO_INCREMENT,
  `nombreProveedor` VARCHAR(45) NOT NULL,
  `telèfon` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`proveedor_id`),
  CONSTRAINT `fk_proveedor_direccion1`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `Exercici1-Optica`.`Direccion` (`direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_direccion1_idx` ON `Exercici1-Optica`.`Proveedor` (`direccion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Compra` (
  `compra_id` INT NOT NULL,
  `fechaDeCompra` DATE NOT NULL,
  `gastoDeCompra` DOUBLE NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`compra_id`),
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `Exercici1-Optica`.`Proveedor` (`proveedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Compra_Proveedor1_idx` ON `Exercici1-Optica`.`Compra` (`proveedor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`marca` (
  `marca_id` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(30) NOT NULL,
  `compra_id` INT NOT NULL,
  PRIMARY KEY (`marca_id`),
  CONSTRAINT `fk_marca_Compra1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `Exercici1-Optica`.`Compra` (`compra_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_marca_Compra1_idx` ON `Exercici1-Optica`.`marca` (`compra_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`gafas` (
  `gafas_id` INT NOT NULL AUTO_INCREMENT,
  `graduacion` VARCHAR(10) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidreo` VARCHAR(45) NOT NULL,
  `preu` DOUBLE NOT NULL,
  `tipoMontura` VARCHAR(45) NULL,
  `marca_marca_id` INT NOT NULL,
  PRIMARY KEY (`gafas_id`),
  CONSTRAINT `fk_gafas_marca1`
    FOREIGN KEY (`marca_marca_id`)
    REFERENCES `Exercici1-Optica`.`marca` (`marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_gafas_marca1_idx` ON `Exercici1-Optica`.`gafas` (`marca_marca_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fechaDeRegistro` DATE NOT NULL,
  `RecomendadoPor` VARCHAR(45) NULL,
  `direccion_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `fk_clientes_direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `Exercici1-Optica`.`Direccion` (`direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_clientes_direccion_idx` ON `Exercici1-Optica`.`Clientes` (`direccion_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Vendedor` (
  `vendedor_id` INT NOT NULL,
  `nombreVendedor` VARCHAR(45) NULL,
  PRIMARY KEY (`vendedor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`Venta` (
  `ventas_id` INT NOT NULL AUTO_INCREMENT,
  `fechaDeVenta` DATE NOT NULL,
  `cliente_id` INT NOT NULL,
  `ingresoVenta` DOUBLE NULL,
  `vendedor_id` INT NOT NULL,
  PRIMARY KEY (`ventas_id`),
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Exercici1-Optica`.`Clientes` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Vendedor1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `Exercici1-Optica`.`Vendedor` (`vendedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ventas_clientes1_idx` ON `Exercici1-Optica`.`Venta` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_Venta_Vendedor1_idx` ON `Exercici1-Optica`.`Venta` (`vendedor_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`DetalleVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`DetalleVenta` (
  `ventas_id` INT NOT NULL,
  `gafas_id` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`ventas_id`, `gafas_id`),
  CONSTRAINT `fk_pedido_has_Gafas_pedido1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `Exercici1-Optica`.`Venta` (`ventas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_has_Gafas_Gafas1`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `Exercici1-Optica`.`gafas` (`gafas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_has_Gafas_Gafas1_idx` ON `Exercici1-Optica`.`DetalleVenta` (`gafas_id` ASC) VISIBLE;

CREATE INDEX `fk_pedido_has_Gafas_pedido1_idx` ON `Exercici1-Optica`.`DetalleVenta` (`ventas_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-Optica`.`DetalleCompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-Optica`.`DetalleCompra` (
  `cantidad` INT NOT NULL,
  `gafas_id` INT NOT NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`gafas_id`, `marca_id`),
  CONSTRAINT `fk_DetalleCompra_gafas1`
    FOREIGN KEY (`gafas_id`)
    REFERENCES `Exercici1-Optica`.`gafas` (`gafas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleCompra_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `Exercici1-Optica`.`marca` (`marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DetalleCompra_gafas1_idx` ON `Exercici1-Optica`.`DetalleCompra` (`gafas_id` ASC) VISIBLE;

CREATE INDEX `fk_DetalleCompra_marca1_idx` ON `Exercici1-Optica`.`DetalleCompra` (`marca_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
