-- MySQL Script generated by MySQL Workbench
-- dom 30 ene 2022 19:41:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exercici2_Pizzeria
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Exercici2_Pizzeria` ;

-- -----------------------------------------------------
-- Schema Exercici2_Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exercici2_Pizzeria` ;
USE `Exercici2_Pizzeria` ;

-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Provincia` (
  `provincia_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`provincia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Localidad` (
  `localidad_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`localidad_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Cliente` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(5) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `provincia_id` INT NOT NULL,
  `localidad_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`),
  CONSTRAINT `fk_Cliente_Provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `Exercici2_Pizzeria`.`Provincia` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_Localidad1`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `Exercici2_Pizzeria`.`Localidad` (`localidad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_Provincia_idx` ON `Exercici2_Pizzeria`.`Cliente` (`provincia_id` ASC) VISIBLE;

CREATE INDEX `fk_Cliente_Localidad1_idx` ON `Exercici2_Pizzeria`.`Cliente` (`localidad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Tienda` (
  `tienda_id` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(12) NOT NULL,
  `provincia_id` INT NOT NULL,
  `localidad_id` INT NOT NULL,
  PRIMARY KEY (`tienda_id`),
  CONSTRAINT `fk_Tienda_Provincia1`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `Exercici2_Pizzeria`.`Provincia` (`provincia_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tienda_Localidad1`
    FOREIGN KEY (`localidad_id`)
    REFERENCES `Exercici2_Pizzeria`.`Localidad` (`localidad_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tienda_Provincia1_idx` ON `Exercici2_Pizzeria`.`Tienda` (`provincia_id` ASC) VISIBLE;

CREATE INDEX `fk_Tienda_Localidad1_idx` ON `Exercici2_Pizzeria`.`Tienda` (`localidad_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Empleado` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `tienda_id` INT NOT NULL,
  `categorialaboral` ENUM("Cocinero", "Repartidor") NOT NULL,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `fk_Empleado_Tienda1`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `Exercici2_Pizzeria`.`Tienda` (`tienda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Empleado_Tienda1_idx` ON `Exercici2_Pizzeria`.`Empleado` (`tienda_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`RecogidaDomicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`RecogidaDomicilio` (
  `recogidaDomicilio_id` INT NOT NULL,
  `fecha/hora` DATETIME NULL,
  `empleado_id` INT NOT NULL,
  PRIMARY KEY (`recogidaDomicilio_id`),
  CONSTRAINT `fk_RecogidaDomicilio_Empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `Exercici2_Pizzeria`.`Empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RecogidaDomicilio_Empleado1_idx` ON `Exercici2_Pizzeria`.`RecogidaDomicilio` (`empleado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`recogidaTienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`recogidaTienda` (
  `recogidatienda_id` INT NOT NULL,
  `Observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`recogidatienda_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`TipoDePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`TipoDePedido` (
  `tipoPedido_id` INT NOT NULL,
  `recogidaDomicilio_id` INT NOT NULL,
  `recogidatienda_id` INT NOT NULL,
  PRIMARY KEY (`tipoPedido_id`),
  CONSTRAINT `fk_TipoDePedido_RecogidaDomicilio1`
    FOREIGN KEY (`recogidaDomicilio_id`)
    REFERENCES `Exercici2_Pizzeria`.`RecogidaDomicilio` (`recogidaDomicilio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TipoDePedido_recogidaTienda1`
    FOREIGN KEY (`recogidatienda_id`)
    REFERENCES `Exercici2_Pizzeria`.`recogidaTienda` (`recogidatienda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TipoDePedido_RecogidaDomicilio1_idx` ON `Exercici2_Pizzeria`.`TipoDePedido` (`recogidaDomicilio_id` ASC) VISIBLE;

CREATE INDEX `fk_TipoDePedido_recogidaTienda1_idx` ON `Exercici2_Pizzeria`.`TipoDePedido` (`recogidatienda_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Pedido` (
  `pedidos_id` INT NOT NULL AUTO_INCREMENT,
  `fecha/hora` DATETIME NOT NULL,
  `cantidad` INT NOT NULL,
  `precioTotal` DOUBLE NOT NULL,
  `cliente_id` INT NOT NULL,
  `tipoPedido_id` INT NOT NULL,
  `Tienda_tienda_id` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`),
  CONSTRAINT `fk_Pedidos_Cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `Exercici2_Pizzeria`.`Cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_TipoDePedido1`
    FOREIGN KEY (`tipoPedido_id`)
    REFERENCES `Exercici2_Pizzeria`.`TipoDePedido` (`tipoPedido_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Tienda1`
    FOREIGN KEY (`Tienda_tienda_id`)
    REFERENCES `Exercici2_Pizzeria`.`Tienda` (`tienda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedidos_Cliente1_idx` ON `Exercici2_Pizzeria`.`Pedido` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_Pedido_TipoDePedido1_idx` ON `Exercici2_Pizzeria`.`Pedido` (`tipoPedido_id` ASC) VISIBLE;

CREATE INDEX `fk_Pedido_Tienda1_idx` ON `Exercici2_Pizzeria`.`Pedido` (`Tienda_tienda_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`CategoriaProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`CategoriaProducto` (
  `categoriaProducto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`categoriaProducto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Producto` (
  `producto_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `Imagen` BLOB NOT NULL,
  `precio` DOUBLE NOT NULL,
  `categoriaProducto_id` INT NOT NULL,
  PRIMARY KEY (`producto_id`),
  CONSTRAINT `fk_Producto_CategoriaProducto1`
    FOREIGN KEY (`categoriaProducto_id`)
    REFERENCES `Exercici2_Pizzeria`.`CategoriaProducto` (`categoriaProducto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Producto_CategoriaProducto1_idx` ON `Exercici2_Pizzeria`.`Producto` (`categoriaProducto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Hamburguesa` (
  `hamburguesa_id` INT NOT NULL AUTO_INCREMENT,
  `categoriaProducto_id` INT NOT NULL,
  PRIMARY KEY (`hamburguesa_id`),
  CONSTRAINT `fk_Hamburguesa_CategoriaProducto1`
    FOREIGN KEY (`categoriaProducto_id`)
    REFERENCES `Exercici2_Pizzeria`.`CategoriaProducto` (`categoriaProducto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Hamburguesa_CategoriaProducto1_idx` ON `Exercici2_Pizzeria`.`Hamburguesa` (`categoriaProducto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Pizza` (
  `pizza_id` INT NOT NULL AUTO_INCREMENT,
  `categoriaProducto_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`),
  CONSTRAINT `fk_Pizza_CategoriaProducto1`
    FOREIGN KEY (`categoriaProducto_id`)
    REFERENCES `Exercici2_Pizzeria`.`CategoriaProducto` (`categoriaProducto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pizza_CategoriaProducto1_idx` ON `Exercici2_Pizzeria`.`Pizza` (`categoriaProducto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Bebida` (
  `bebida_id` INT NOT NULL AUTO_INCREMENT,
  `categoriaProducto_id` INT NOT NULL,
  PRIMARY KEY (`bebida_id`),
  CONSTRAINT `fk_Bebida_CategoriaProducto1`
    FOREIGN KEY (`categoriaProducto_id`)
    REFERENCES `Exercici2_Pizzeria`.`CategoriaProducto` (`categoriaProducto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Bebida_CategoriaProducto1_idx` ON `Exercici2_Pizzeria`.`Bebida` (`categoriaProducto_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`DetallePedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`DetallePedido` (
  `pedidos_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`pedidos_id`, `producto_id`),
  CONSTRAINT `fk_Pedido_has_Producto_Pedido1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `Exercici2_Pizzeria`.`Pedido` (`pedidos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Producto_Producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `Exercici2_Pizzeria`.`Producto` (`producto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Pedido_has_Producto_Producto1_idx` ON `Exercici2_Pizzeria`.`DetallePedido` (`producto_id` ASC) VISIBLE;

CREATE INDEX `fk_Pedido_has_Producto_Pedido1_idx` ON `Exercici2_Pizzeria`.`DetallePedido` (`pedidos_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici2_Pizzeria`.`Repartidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici2_Pizzeria`.`Repartidor` (
  `repartidor_id` INT NOT NULL,
  PRIMARY KEY (`repartidor_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
