-- MySQL Script generated by MySQL Workbench
-- dom 30 ene 2022 19:44:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exercici1-YouTube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Exercici1-YouTube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exercici1-YouTube` ;
USE `Exercici1-YouTube` ;

-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Usuario` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  `nombreUsuario` VARCHAR(45) NULL,
  `fechaDeNacimiento` DATETIME NOT NULL,
  `Sexo` ENUM('M', 'F') NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Estados` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `estado` ENUM('Public', 'Hidden', 'Private') NOT NULL DEFAULT 'Public',
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Video` (
  `video_id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `duración` VARCHAR(45) NOT NULL,
  `thumnail` BLOB NOT NULL,
  `reproducciones` INT NOT NULL,
  `PublicadoPor` VARCHAR(45) NOT NULL,
  `fechaDePublicacion` DATE NOT NULL,
  `horaDePublicacion` TIME NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`video_id`),
  CONSTRAINT `fk_Video_Estados1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `Exercici1-YouTube`.`Estados` (`estado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Video_Estados1_idx` ON `Exercici1-YouTube`.`Video` (`estado_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Etiquetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Etiquetas` (
  `etiqueta_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `Video_video_id` INT NOT NULL,
  PRIMARY KEY (`etiqueta_id`),
  CONSTRAINT `fk_Etiquetas_Video1`
    FOREIGN KEY (`Video_video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Etiquetas_Video1_idx` ON `Exercici1-YouTube`.`Etiquetas` (`Video_video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Canal` (
  `canal_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fechaDeCreacion` DATETIME NOT NULL,
  PRIMARY KEY (`canal_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`PlayList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`PlayList` (
  `playList_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaDeCreacion` DATE NOT NULL,
  `estado` ENUM('Publico', 'Privado') NOT NULL,
  PRIMARY KEY (`playList_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`registroComentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`registroComentarios` (
  `comentarios_id` INT NOT NULL AUTO_INCREMENT,
  `Comentario` VARCHAR(45) NOT NULL,
  `like` INT NOT NULL,
  `dislikes` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `usuario_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`comentarios_id`),
  CONSTRAINT `fk_registroComentarios_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Exercici1-YouTube`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroComentarios_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_registroComentarios_Usuario1_idx` ON `Exercici1-YouTube`.`registroComentarios` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_registroComentarios_Video1_idx` ON `Exercici1-YouTube`.`registroComentarios` (`video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Subscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Subscripcion` (
  `subscripcion_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `canal_id` INT NOT NULL,
  PRIMARY KEY (`subscripcion_id`),
  CONSTRAINT `fk_Subscripcion_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Exercici1-YouTube`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscripcion_Canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `Exercici1-YouTube`.`Canal` (`canal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Subscripcion_Usuario1_idx` ON `Exercici1-YouTube`.`Subscripcion` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_Subscripcion_Canal1_idx` ON `Exercici1-YouTube`.`Subscripcion` (`canal_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`VerVideos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`VerVideos` (
  `usuario_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `video_id`),
  CONSTRAINT `fk_VerVideos_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Exercici1-YouTube`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VerVideos_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_VerVideos_Usuario1_idx` ON `Exercici1-YouTube`.`VerVideos` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_VerVideos_Video1_idx` ON `Exercici1-YouTube`.`VerVideos` (`video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`CrearVideos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`CrearVideos` (
  `canal_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`canal_id`, `video_id`),
  CONSTRAINT `fk_CrearVideos_Canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `Exercici1-YouTube`.`Canal` (`canal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CrearVideos_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CrearVideos_Video1_idx` ON `Exercici1-YouTube`.`CrearVideos` (`video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`RegistroLikes/Dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`RegistroLikes/Dislikes` (
  `likes/dislikes_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `usuario_id` INT NOT NULL,
  `numeroLikes` INT NOT NULL,
  `numerodislikes` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`likes/dislikes_id`),
  CONSTRAINT `fk_RegistroLikes/Dislikes_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Exercici1-YouTube`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroLikes/Dislikes_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RegistroLikes/Dislikes_Usuario1_idx` ON `Exercici1-YouTube`.`RegistroLikes/Dislikes` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_RegistroLikes/Dislikes_Video1_idx` ON `Exercici1-YouTube`.`RegistroLikes/Dislikes` (`video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`DetalleplayList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`DetalleplayList` (
  `playList_id` INT NOT NULL,
  `video_id` INT NOT NULL,
  PRIMARY KEY (`playList_id`, `video_id`),
  CONSTRAINT `fk_DetalleplayList_PlayList1`
    FOREIGN KEY (`playList_id`)
    REFERENCES `Exercici1-YouTube`.`PlayList` (`playList_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetalleplayList_Video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Exercici1-YouTube`.`Video` (`video_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DetalleplayList_PlayList1_idx` ON `Exercici1-YouTube`.`DetalleplayList` (`playList_id` ASC) VISIBLE;

CREATE INDEX `fk_DetalleplayList_Video1_idx` ON `Exercici1-YouTube`.`DetalleplayList` (`video_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`CreacionCanal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`CreacionCanal` (
  `usuario_id` INT NOT NULL,
  `Canal_canal_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `Canal_canal_id`),
  CONSTRAINT `fk_CreacionCanal_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `Exercici1-YouTube`.`Usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CreacionCanal_Canal1`
    FOREIGN KEY (`Canal_canal_id`)
    REFERENCES `Exercici1-YouTube`.`Canal` (`canal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CreacionCanal_Canal1_idx` ON `Exercici1-YouTube`.`CreacionCanal` (`Canal_canal_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Exercici1-YouTube`.`Crearplaylist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exercici1-YouTube`.`Crearplaylist` (
  `canal_id` INT NOT NULL,
  `playList_id` INT NOT NULL,
  PRIMARY KEY (`canal_id`, `playList_id`),
  CONSTRAINT `fk_Crearplaylist_Canal1`
    FOREIGN KEY (`canal_id`)
    REFERENCES `Exercici1-YouTube`.`Canal` (`canal_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Crearplaylist_PlayList1`
    FOREIGN KEY (`playList_id`)
    REFERENCES `Exercici1-YouTube`.`PlayList` (`playList_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Crearplaylist_Canal1_idx` ON `Exercici1-YouTube`.`Crearplaylist` (`canal_id` ASC) VISIBLE;

CREATE INDEX `fk_Crearplaylist_PlayList1_idx` ON `Exercici1-YouTube`.`Crearplaylist` (`playList_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
